name = "UniversalPricing"
uuid = "8110a956-2552-469c-bcd0-ddf925ed1df7"
authors = ["SciQuant"]
version = "0.1.0"

[deps]
LsqFit = "2fda8390-95c7-5789-9bda-21331edee243"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StochasticDiffEq = "789caeaf-c7a9-5a7d-9973-96adeb23e2a0"
UniversalDynamics = "e34ebe0d-adf9-4359-84c2-dfdf884d416d"

[compat]
Reexport = "1.0"
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
